import { createFileRoute } from "@tanstack/react-router";
import { LegalPageLayout } from "@/components/LegalPageLayout";

export const Route = createFileRoute("/recovery-plus/ai-disclaimer")({
  head: () => ({
    meta: [
      { title: "AI & Medical Disclaimer — Recovery Plus | Aftermath Studio" },
      {
        name: "description",
        content:
          "The intended use and limitations of the AI features available within Recovery Plus.",
      },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: AIDisclaimerPage,
});

const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;
const UL = ({ items }: { items: string[] }) => (
  <ul className="list-disc space-y-1 pl-6">
    {items.map((i) => (
      <li key={i}>{i}</li>
    ))}
  </ul>
);

function AIDisclaimerPage() {
  return (
    <LegalPageLayout
      title="AI & Medical Disclaimer"
      intro={
        <>
          <P>
            This AI &amp; Medical Disclaimer explains the intended use and limitations of the
            artificial intelligence (&ldquo;AI&rdquo;) features available within Recovery Plus. By
            using the AI features of Recovery Plus, you acknowledge that you have read, understood,
            and agreed to this Disclaimer.
          </P>
          <P>
            This document should be read together with the Terms &amp; Conditions, Privacy Policy,
            and User Agreement &amp; Community Guidelines.
          </P>
        </>
      }
      sections={[
        {
          heading: "1. The Purpose of Recovery Plus AI",
          body: (
            <>
              <P>Recovery Plus AI has been developed to support individuals on their personal recovery journey by providing:</P>
              <UL
                items={[
                  "Educational information",
                  "Recovery guidance",
                  "Motivation and encouragement",
                  "Journaling assistance",
                  "Goal setting support",
                  "Reflection prompts",
                  "Habit-building suggestions",
                  "Accountability reminders",
                  "General wellbeing information",
                ]}
              />
              <P>
                Recovery Plus AI is intended to complement your recovery journey and should not
                replace qualified professional care.
              </P>
            </>
          ),
        },
        {
          heading: "2. Recovery Plus AI is Not a Healthcare Professional",
          body: (
            <>
              <P>Recovery Plus AI is not:</P>
              <UL
                items={[
                  "A doctor",
                  "A psychiatrist",
                  "A psychologist",
                  "A therapist",
                  "A counsellor",
                  "A social worker",
                  "A nurse",
                  "A pharmacist",
                  "A lawyer",
                  "A financial adviser",
                  "An emergency service",
                ]}
              />
              <P>
                Any information generated by the AI should be treated as general educational or
                supportive information only.
              </P>
            </>
          ),
        },
        {
          heading: "3. No Medical Advice",
          body: (
            <>
              <P>Nothing generated by Recovery Plus AI should be interpreted as:</P>
              <UL
                items={[
                  "Medical advice",
                  "Clinical advice",
                  "Mental health diagnosis",
                  "Addiction diagnosis",
                  "Prescription guidance",
                  "Treatment recommendations",
                  "Emergency instructions",
                ]}
              />
              <P>
                Always seek advice from appropriately qualified professionals regarding medical,
                psychological, psychiatric, addiction, or legal matters.
              </P>
            </>
          ),
        },
        {
          heading: "4. Recovery Outcomes",
          body: (
            <>
              <P>Recovery is different for every individual. Recovery Plus AI cannot:</P>
              <UL
                items={[
                  "Guarantee sobriety",
                  "Prevent relapse",
                  "Predict recovery outcomes",
                  "Guarantee treatment success",
                  "Replace professional rehabilitation programmes",
                ]}
              />
            </>
          ),
        },
        {
          heading: "5. Accuracy of AI Responses",
          body: (
            <UL
              items={[
                "AI can make mistakes",
                "AI may misunderstand questions",
                "AI may generate incomplete responses",
                "AI may provide outdated information",
                "AI should not be relied upon without appropriate judgement",
              ]}
            />
          ),
        },
        {
          heading: "6. Crisis Situations",
          body: (
            <>
              <P>Recovery Plus AI must never be relied upon during emergencies. If you are:</P>
              <UL
                items={[
                  "Thinking about harming yourself",
                  "Thinking about harming another person",
                  "Experiencing a medical emergency",
                  "Experiencing severe withdrawal symptoms",
                  "Experiencing a mental health crisis",
                  "In immediate danger",
                ]}
              />
              <P>
                contact your local emergency services or a qualified healthcare professional
                immediately.
              </P>
            </>
          ),
        },
        {
          heading: "7. Medication",
          body: (
            <>
              <P>Recovery Plus AI cannot:</P>
              <UL
                items={[
                  "Prescribe medication",
                  "Recommend prescription dosages",
                  "Advise users to stop medication",
                  "Replace advice provided by licensed healthcare professionals",
                ]}
              />
            </>
          ),
        },
        {
          heading: "8. Treatment Decisions",
          body: (
            <>
              <P>Decisions regarding entering rehabilitation, leaving treatment, medication, counselling, therapy, detoxification, or hospital admission should always be made with qualified healthcare professionals.</P>
              <P>Recovery Plus AI is intended to support — not replace — professional decision-making.</P>
            </>
          ),
        },
        {
          heading: "9. User Responsibility",
          body: (
            <UL
              items={[
                "You remain responsible for your own decisions",
                "You will use your own judgement",
                "You will seek professional assistance where appropriate",
                "You understand the limitations of artificial intelligence",
              ]}
            />
          ),
        },
        {
          heading: "10. AI Conversation Storage",
          body: (
            <P>
              To improve your experience, Recovery Plus may securely store AI conversations
              associated with your account. Conversation storage is governed by the Recovery Plus
              Privacy Policy.
            </P>
          ),
        },
        {
          heading: "11. Continuous Improvement",
          body: (
            <P>
              Recovery Plus AI is continually being improved. Responses, capabilities, and
              functionality may change as improvements are introduced to accuracy, safety,
              reliability, and user experience.
            </P>
          ),
        },
        {
          heading: "12. No Guarantee of Availability",
          body: (
            <>
              <P>Recovery Plus AI is provided on an &ldquo;as available&rdquo; basis and may become temporarily unavailable due to:</P>
              <UL
                items={[
                  "Maintenance",
                  "Technical failures",
                  "Network interruptions",
                  "Service provider outages",
                  "System upgrades",
                ]}
              />
            </>
          ),
        },
        {
          heading: "13. Limitation of Liability",
          body: (
            <>
              <P>To the maximum extent permitted by applicable law, Aftermath Studio shall not be liable for any loss, damage, injury, or claim arising from:</P>
              <UL
                items={[
                  "Reliance upon AI-generated responses",
                  "Misinterpretation of AI information",
                  "Decisions made by users",
                  "Delays or interruptions in AI availability",
                  "Errors or omissions in AI-generated content",
                ]}
              />
            </>
          ),
        },
        {
          heading: "14. Future AI Features",
          body: (
            <P>
              Future versions may include voice conversations, personalised coaching, predictive
              recovery insights, expanded journaling support, and accountability assistance. Where
              new AI capabilities materially affect the processing of personal information, this
              Disclaimer and the Privacy Policy will be updated accordingly.
            </P>
          ),
        },
        {
          heading: "15. Changes to this Disclaimer",
          body: (
            <P>
              Material changes will be communicated via in-app notifications, email, or
              announcements on aftermathstudio.co.za. Continued use constitutes acceptance of the
              revised Disclaimer.
            </P>
          ),
        },
        {
          heading: "16. Contact Information",
          body: (
            <P>
              Questions regarding this AI &amp; Medical Disclaimer may be directed to
              contact@aftermathstudio.co.za.
            </P>
          ),
        },
      ]}
      closer={
        <>
          <h2 className="text-xl font-semibold text-foreground md:text-2xl">Final Statement</h2>
          <P>
            Recovery Plus AI has been created to encourage, educate, organise, and support
            individuals throughout their recovery journey. It is designed to work alongside — not
            in place of — qualified healthcare professionals, trusted support networks, and
            personal responsibility.
          </P>
        </>
      }
    />
  );
}
