/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZizieRouteImport } from './routes/zizie'
import { Route as UbuntuTheFallRouteImport } from './routes/ubuntu-the-fall'
import { Route as RecoveryPlusRouteImport } from './routes/recovery-plus'
import { Route as HabitWealthRouteImport } from './routes/habit-wealth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecoveryPlusIndexRouteImport } from './routes/recovery-plus.index'
import { Route as RecoveryPlusTermsRouteImport } from './routes/recovery-plus.terms'
import { Route as RecoveryPlusPrivacyPolicyRouteImport } from './routes/recovery-plus.privacy-policy'
import { Route as RecoveryPlusDataRetentionRouteImport } from './routes/recovery-plus.data-retention'
import { Route as RecoveryPlusCommunityGuidelinesRouteImport } from './routes/recovery-plus.community-guidelines'
import { Route as RecoveryPlusAiDisclaimerRouteImport } from './routes/recovery-plus.ai-disclaimer'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as ApiPublicAccountDeletionRouteImport } from './routes/api/public/account-deletion'

const ZizieRoute = ZizieRouteImport.update({
  id: '/zizie',
  path: '/zizie',
  getParentRoute: () => rootRouteImport,
} as any)
const UbuntuTheFallRoute = UbuntuTheFallRouteImport.update({
  id: '/ubuntu-the-fall',
  path: '/ubuntu-the-fall',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryPlusRoute = RecoveryPlusRouteImport.update({
  id: '/recovery-plus',
  path: '/recovery-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitWealthRoute = HabitWealthRouteImport.update({
  id: '/habit-wealth',
  path: '/habit-wealth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryPlusIndexRoute = RecoveryPlusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecoveryPlusRoute,
} as any)
const RecoveryPlusTermsRoute = RecoveryPlusTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => RecoveryPlusRoute,
} as any)
const RecoveryPlusPrivacyPolicyRoute =
  RecoveryPlusPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => RecoveryPlusRoute,
  } as any)
const RecoveryPlusDataRetentionRoute =
  RecoveryPlusDataRetentionRouteImport.update({
    id: '/data-retention',
    path: '/data-retention',
    getParentRoute: () => RecoveryPlusRoute,
  } as any)
const RecoveryPlusCommunityGuidelinesRoute =
  RecoveryPlusCommunityGuidelinesRouteImport.update({
    id: '/community-guidelines',
    path: '/community-guidelines',
    getParentRoute: () => RecoveryPlusRoute,
  } as any)
const RecoveryPlusAiDisclaimerRoute =
  RecoveryPlusAiDisclaimerRouteImport.update({
    id: '/ai-disclaimer',
    path: '/ai-disclaimer',
    getParentRoute: () => RecoveryPlusRoute,
  } as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccountDeletionRoute =
  ApiPublicAccountDeletionRouteImport.update({
    id: '/api/public/account-deletion',
    path: '/api/public/account-deletion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habit-wealth': typeof HabitWealthRoute
  '/recovery-plus': typeof RecoveryPlusRouteWithChildren
  '/ubuntu-the-fall': typeof UbuntuTheFallRoute
  '/zizie': typeof ZizieRoute
  '/recovery-plus/ai-disclaimer': typeof RecoveryPlusAiDisclaimerRoute
  '/recovery-plus/community-guidelines': typeof RecoveryPlusCommunityGuidelinesRoute
  '/recovery-plus/data-retention': typeof RecoveryPlusDataRetentionRoute
  '/recovery-plus/privacy-policy': typeof RecoveryPlusPrivacyPolicyRoute
  '/recovery-plus/terms': typeof RecoveryPlusTermsRoute
  '/recovery-plus/': typeof RecoveryPlusIndexRoute
  '/api/public/account-deletion': typeof ApiPublicAccountDeletionRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habit-wealth': typeof HabitWealthRoute
  '/ubuntu-the-fall': typeof UbuntuTheFallRoute
  '/zizie': typeof ZizieRoute
  '/recovery-plus/ai-disclaimer': typeof RecoveryPlusAiDisclaimerRoute
  '/recovery-plus/community-guidelines': typeof RecoveryPlusCommunityGuidelinesRoute
  '/recovery-plus/data-retention': typeof RecoveryPlusDataRetentionRoute
  '/recovery-plus/privacy-policy': typeof RecoveryPlusPrivacyPolicyRoute
  '/recovery-plus/terms': typeof RecoveryPlusTermsRoute
  '/recovery-plus': typeof RecoveryPlusIndexRoute
  '/api/public/account-deletion': typeof ApiPublicAccountDeletionRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habit-wealth': typeof HabitWealthRoute
  '/recovery-plus': typeof RecoveryPlusRouteWithChildren
  '/ubuntu-the-fall': typeof UbuntuTheFallRoute
  '/zizie': typeof ZizieRoute
  '/recovery-plus/ai-disclaimer': typeof RecoveryPlusAiDisclaimerRoute
  '/recovery-plus/community-guidelines': typeof RecoveryPlusCommunityGuidelinesRoute
  '/recovery-plus/data-retention': typeof RecoveryPlusDataRetentionRoute
  '/recovery-plus/privacy-policy': typeof RecoveryPlusPrivacyPolicyRoute
  '/recovery-plus/terms': typeof RecoveryPlusTermsRoute
  '/recovery-plus/': typeof RecoveryPlusIndexRoute
  '/api/public/account-deletion': typeof ApiPublicAccountDeletionRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/habit-wealth'
    | '/recovery-plus'
    | '/ubuntu-the-fall'
    | '/zizie'
    | '/recovery-plus/ai-disclaimer'
    | '/recovery-plus/community-guidelines'
    | '/recovery-plus/data-retention'
    | '/recovery-plus/privacy-policy'
    | '/recovery-plus/terms'
    | '/recovery-plus/'
    | '/api/public/account-deletion'
    | '/api/public/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/habit-wealth'
    | '/ubuntu-the-fall'
    | '/zizie'
    | '/recovery-plus/ai-disclaimer'
    | '/recovery-plus/community-guidelines'
    | '/recovery-plus/data-retention'
    | '/recovery-plus/privacy-policy'
    | '/recovery-plus/terms'
    | '/recovery-plus'
    | '/api/public/account-deletion'
    | '/api/public/waitlist'
  id:
    | '__root__'
    | '/'
    | '/habit-wealth'
    | '/recovery-plus'
    | '/ubuntu-the-fall'
    | '/zizie'
    | '/recovery-plus/ai-disclaimer'
    | '/recovery-plus/community-guidelines'
    | '/recovery-plus/data-retention'
    | '/recovery-plus/privacy-policy'
    | '/recovery-plus/terms'
    | '/recovery-plus/'
    | '/api/public/account-deletion'
    | '/api/public/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitWealthRoute: typeof HabitWealthRoute
  RecoveryPlusRoute: typeof RecoveryPlusRouteWithChildren
  UbuntuTheFallRoute: typeof UbuntuTheFallRoute
  ZizieRoute: typeof ZizieRoute
  ApiPublicAccountDeletionRoute: typeof ApiPublicAccountDeletionRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zizie': {
      id: '/zizie'
      path: '/zizie'
      fullPath: '/zizie'
      preLoaderRoute: typeof ZizieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubuntu-the-fall': {
      id: '/ubuntu-the-fall'
      path: '/ubuntu-the-fall'
      fullPath: '/ubuntu-the-fall'
      preLoaderRoute: typeof UbuntuTheFallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-plus': {
      id: '/recovery-plus'
      path: '/recovery-plus'
      fullPath: '/recovery-plus'
      preLoaderRoute: typeof RecoveryPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habit-wealth': {
      id: '/habit-wealth'
      path: '/habit-wealth'
      fullPath: '/habit-wealth'
      preLoaderRoute: typeof HabitWealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-plus/': {
      id: '/recovery-plus/'
      path: '/'
      fullPath: '/recovery-plus/'
      preLoaderRoute: typeof RecoveryPlusIndexRouteImport
      parentRoute: typeof RecoveryPlusRoute
    }
    '/recovery-plus/terms': {
      id: '/recovery-plus/terms'
      path: '/terms'
      fullPath: '/recovery-plus/terms'
      preLoaderRoute: typeof RecoveryPlusTermsRouteImport
      parentRoute: typeof RecoveryPlusRoute
    }
    '/recovery-plus/privacy-policy': {
      id: '/recovery-plus/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/recovery-plus/privacy-policy'
      preLoaderRoute: typeof RecoveryPlusPrivacyPolicyRouteImport
      parentRoute: typeof RecoveryPlusRoute
    }
    '/recovery-plus/data-retention': {
      id: '/recovery-plus/data-retention'
      path: '/data-retention'
      fullPath: '/recovery-plus/data-retention'
      preLoaderRoute: typeof RecoveryPlusDataRetentionRouteImport
      parentRoute: typeof RecoveryPlusRoute
    }
    '/recovery-plus/community-guidelines': {
      id: '/recovery-plus/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/recovery-plus/community-guidelines'
      preLoaderRoute: typeof RecoveryPlusCommunityGuidelinesRouteImport
      parentRoute: typeof RecoveryPlusRoute
    }
    '/recovery-plus/ai-disclaimer': {
      id: '/recovery-plus/ai-disclaimer'
      path: '/ai-disclaimer'
      fullPath: '/recovery-plus/ai-disclaimer'
      preLoaderRoute: typeof RecoveryPlusAiDisclaimerRouteImport
      parentRoute: typeof RecoveryPlusRoute
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/account-deletion': {
      id: '/api/public/account-deletion'
      path: '/api/public/account-deletion'
      fullPath: '/api/public/account-deletion'
      preLoaderRoute: typeof ApiPublicAccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecoveryPlusRouteChildren {
  RecoveryPlusAiDisclaimerRoute: typeof RecoveryPlusAiDisclaimerRoute
  RecoveryPlusCommunityGuidelinesRoute: typeof RecoveryPlusCommunityGuidelinesRoute
  RecoveryPlusDataRetentionRoute: typeof RecoveryPlusDataRetentionRoute
  RecoveryPlusPrivacyPolicyRoute: typeof RecoveryPlusPrivacyPolicyRoute
  RecoveryPlusTermsRoute: typeof RecoveryPlusTermsRoute
  RecoveryPlusIndexRoute: typeof RecoveryPlusIndexRoute
}

const RecoveryPlusRouteChildren: RecoveryPlusRouteChildren = {
  RecoveryPlusAiDisclaimerRoute: RecoveryPlusAiDisclaimerRoute,
  RecoveryPlusCommunityGuidelinesRoute: RecoveryPlusCommunityGuidelinesRoute,
  RecoveryPlusDataRetentionRoute: RecoveryPlusDataRetentionRoute,
  RecoveryPlusPrivacyPolicyRoute: RecoveryPlusPrivacyPolicyRoute,
  RecoveryPlusTermsRoute: RecoveryPlusTermsRoute,
  RecoveryPlusIndexRoute: RecoveryPlusIndexRoute,
}

const RecoveryPlusRouteWithChildren = RecoveryPlusRoute._addFileChildren(
  RecoveryPlusRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitWealthRoute: HabitWealthRoute,
  RecoveryPlusRoute: RecoveryPlusRouteWithChildren,
  UbuntuTheFallRoute: UbuntuTheFallRoute,
  ZizieRoute: ZizieRoute,
  ApiPublicAccountDeletionRoute: ApiPublicAccountDeletionRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
